# t-rex configuration

[service.mvt]
viewer = true

[datasource]
type = "postgis"
url = "postgresql://ubuntu:-ubuntu-@localhost/vtile"

[grid]
# Predefined grids: web_mercator, wgs84
predefined = "web_mercator"

[[tileset]]
name = "lines"
extent = [-5.05458, 41.90090, 9.45420, 51.08534]
[[tileset.layer]]
name = "lines"
table_name = "lines"
geometry_field = "geom"
geometry_type = "MULTILINESTRING"
srid = 3857
#fid_field = "id"
buffer_size = 0
simplify = true
query_limit = 1000
[[tileset.layer.query]]
sql = """SELECT geom,"id","name","code","operator","network","mode","colour" FROM lines100 WHERE geom && !bbox!"""
[[tileset.layer.query]]
minzoom = 14
maxzoom = 16
sql = """SELECT geom,"id","name","code","operator","network","mode","colour" FROM lines50 WHERE geom && !bbox!"""
[[tileset.layer.query]]
minzoom = 16
maxzoom = 22
sql = """SELECT geom,"id","name","code","operator","network","mode","colour" FROM lines10 WHERE geom && !bbox!"""

[[tileset]]
name = "admin_level_poly"
[[tileset.layer]]
name = "admin_level_poly"
table_name = "import.osm_admin_poly"
geometry_field = "geometry"
geometry_type = "POLYGON"
srid = 3857
#fid_field = "id"
buffer_size = 0
simplify = true
query_limit = 1000

[[tileset]]
name = "poc_nantes"
[[tileset.layer]]
name = "poc_nantes"
table_name = "tan_group"
geometry_field = "geom"
geometry_type = "MULTILINESTRING"
srid = 3857
#fid_field = "id"
buffer_size = 0
simplify = true
query_limit = 1000
[[tileset.layer.query]]
sql = """select d.*, g.count, array_position(codes, d.code) as offset_order
from tan_group g left join tan_detail d
on g.geom = d.geom
WHERE g.geom && !bbox!"""

#[cache.file]
#base = "/srv/mvtcache"
#baseurl = "http://example.com/tiles"

[webserver]
# Bind address. Use 0.0.0.0 to listen on all adresses.
bind = "0.0.0.0"
port = 6767
threads = 4
#cache_control_max_age = 43200
